name: Feature Request
description: Suggest a new feature for LyraJS Core
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature for LyraJS Core! 🎉

        Please describe your idea in detail to help us understand your needs.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? Is your feature request related to a problem?
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work? Describe the desired behavior.
      placeholder: |
        I would like to be able to...

        Example usage:
        ```typescript
        // Code example
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives or workarounds have you considered?
      placeholder: I've tried... / Another approach could be...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component of LyraJS Core would this feature affect?
      options:
        - ORM / Entities
        - Repositories
        - QueryBuilder
        - Maestro CLI
        - Authentication
        - Middleware
        - Configuration
        - Database Migrations
        - TypeScript Types
        - Other / Multiple
    validations:
      required: true

  - type: checkboxes
    id: willingness
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I'm willing to submit a pull request to implement this feature
          required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Related projects, links to similar implementations, etc.
